name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22

      - name: checkout
        uses: actions/checkout@v4

      - name: deps
        run: make deps

      - name: build
        run: make build
